openapi: 3.0.0
info:
  version: '0.1'
  title: 'Internmap'
  license:
    name: MIT
servers:
  - url: 'localhost:6543'
paths:
  /internships:
    get:
      summary: 'GET ALL Internships'
      operationId: getInternships
      tags:
        - intern
      responses:
        '200':
          description: '200 Ok'
          content:
            application/json:
              schema:
                 type: array
                 items:
                  $ref: '#/components/schemas/Internship'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /login:
    post:
      summary: 'POST LOGIN'
      operationId: postLogin
      tags:
        - login
      responses:
        '200':
          description: '200 Ok'
          content:
            application/json:
              schema:
                type: string
        '401':
          description: '401 Unauthorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error:
                  status: 'UNAUTHORIZED'
                  message: 'Bad credentials.'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /whoiam:
    get:
      summary: 'GET whoiam'
      operationId: getWhoiam
      tags:
        - whoiam
      security:
        - bearerAuth: []
      responses:
        '200':
          description: '200 Ok'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: '401 Unauthorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error:
                  status: 'UNAUTHORIZED'
                  message: 'Bad credentials.'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /upload:
    get:
      summary: 'GET Upload'
      operationId: getUpload
      tags:
        - upload
      security:
        - bearerAuth: []
      responses:
        '200':
          description: '200 Ok'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Upload'
        '401':
          description: '401 Unauthorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error:
                  status: 'UNAUTHORIZED'
                  message: 'Bad credentials.'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: 'POST Upload'
      operationId: postUpload
      tags:
        - upload
      security:
        - bearerAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: '200 Ok'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Upload'
        '401':
          description: '401 Unauthorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error:
                  status: 'UNAUTHORIZED'
                  message: 'Bad credentials.'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        
components:
  schemas:
    Internship:
      type: object
      required:
        - id
        - name
        - latitude
        - longitude
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        latitude:
          type: integer
        longitude:
          type: integer
        email:
          type: string
        tel:
          type: string
    User:
      type: object
      required:
        - id
        - email
      properties:
        id:
          type: integer
        email:
          type: string
    Upload:
      type: object
      required:
        - id
        - date
        - nbInternships
        - nbCategories
      properties:
        id:
          type: integer
        date:
          type: string
        nbInternships:
          type: integer
        nbCategories:
          type: integer
        errors:
          type: array
          items:
            type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        status:
          type: string
        message:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
    - bearerAuth: []
    